import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/current-admin";
import { adminSessionsReader, frenchName, frenchTrainingTitle } from "@/lib/admin/sessions.read";
import { saveSessionAction } from "@/lib/admin/sessions.actions";
import { LifecyclePanel, SessionHeader, Trainers, dateInput, sessionLocation, sessionPrice, statusLabel } from "../components";
import { SessionForm } from "../session-form";

export default async function SessionDetailPage({ params }: { params: Promise<{ sessionId: string }> }) { await requireAdmin(); const { sessionId } = await params; const [session, experts] = await Promise.all([adminSessionsReader.detail(sessionId), adminSessionsReader.activeExperts()]); if (!session) notFound(); const mutable = session.status === "DRAFT" || session.status === "OPEN" || session.status === "CLOSED"; const domain = frenchName(session.training.trainingTopic.trainingDomain.translations), topic = frenchName(session.training.trainingTopic.translations); return <div className="space-y-10"><SessionHeader title={frenchTrainingTitle(session.training)} description={`${domain} → ${topic} · ${statusLabel[session.status]}`} actions={<Link href="/admin/sessions" className="wb-focus inline-flex min-h-10 items-center border-b border-current text-sm font-medium">Retour aux sessions</Link>} /><div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_18rem]"><section>{mutable ? <SessionForm action={saveSessionAction} sessionId={session.id} initial={{ startDate: dateInput(session.startDate), endDate: dateInput(session.endDate), registrationDeadline: dateInput(session.registrationDeadline), deliveryMode: session.deliveryMode, country: session.country ?? "", city: session.city ?? "", venue: session.venue ?? "", pricingMode: session.pricingMode, price: session.price?.toString() ?? "", currency: session.currency ?? "", capacity: session.capacity?.toString() ?? "" }} /> : <div className="space-y-7 border-y border-[#c8cac0] py-7"><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">ARCHIVE DE SESSION</p><dl className="grid gap-6 sm:grid-cols-2"><div><dt className="text-sm text-[#626862]">Dates</dt><dd className="mt-1 font-medium">{dateInput(session.startDate)} — {dateInput(session.endDate)}</dd></div><div><dt className="text-sm text-[#626862]">Inscriptions</dt><dd className="mt-1 font-medium">{session.registrationDeadline ? dateInput(session.registrationDeadline) : "Sans date limite"}</dd></div><div><dt className="text-sm text-[#626862]">Modalité</dt><dd className="mt-1 font-medium">{sessionLocation(session)}</dd></div><div><dt className="text-sm text-[#626862]">Tarification</dt><dd className="mt-1 font-medium">{sessionPrice(session)}</dd></div><div><dt className="text-sm text-[#626862]">Capacité</dt><dd className="mt-1 font-medium">{session.capacity ? `${session.capacity} participants` : "Non précisée"}</dd></div></dl></div>}<div className="mt-10"><Trainers id={session.id} assignments={session.expertAssignments} experts={experts} mutable={mutable} /></div></section><LifecyclePanel id={session.id} status={session.status} /></div></div>; }
