import Link from "next/link";
import { CatalogueStatus, Locale } from "@prisma/client";
import { catalogueLocales, localeLabels } from "@/lib/admin/catalogue.read";
import { lifecycleAction, translationPublicationAction } from "@/lib/admin/catalogue.actions";
import { CatalogueActionForm } from "./catalogue-form";

export const frenchName = (translations: { locale: Locale; name?: string; title?: string }[]) => translations.find((translation) => translation.locale === Locale.FR)?.name ?? translations.find((translation) => translation.locale === Locale.FR)?.title ?? translations[0]?.name ?? translations[0]?.title ?? "Sans traduction française";
export const statusLabel: Record<CatalogueStatus, string> = { DRAFT: "Brouillon", PUBLISHED: "Publié", ARCHIVED: "Archivé" };

export function CatalogueHeader({ title, description, actions }: { title: string; description: string; actions?: React.ReactNode }) {
  return <header className="flex flex-wrap items-end justify-between gap-6 border-b border-[#18211d] pb-7"><div><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">FORMATIONS</p><h1 className="mt-4 text-3xl font-semibold tracking-[-0.035em] md:text-4xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#626862]">{description}</p></div>{actions}</header>;
}
export function QuietLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="wb-action wb-focus inline-flex min-h-10 items-center border-b border-current text-sm font-medium">{children}</Link>; }
export function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="wb-focus inline-flex min-h-11 items-center bg-[#15382f] px-5 py-2 text-sm font-medium text-white hover:bg-[#245b49]">{children}</Link>; }
export function LocaleTabs({ path, selected, translations }: { path: string; selected: Locale; translations: { locale: Locale; isPublished: boolean }[] }) {
  return <nav aria-label="Langue du contenu" className="flex flex-wrap gap-x-5 gap-y-2 border-b border-[#c8cac0] pb-3">{catalogueLocales.map((locale) => { const entry = translations.find((translation) => translation.locale === locale); return <Link key={locale} href={`${path}?locale=${locale}`} aria-current={locale === selected ? "page" : undefined} className={`wb-focus border-b-2 pb-2 text-sm ${locale === selected ? "border-[#245b49] font-semibold text-[#18211d]" : "border-transparent text-[#626862] hover:text-[#18211d]"}`}>{localeLabels[locale]} <span className="ml-1 text-xs">{entry ? entry.isPublished ? "· visible" : "· non publiée" : "· à renseigner"}</span></Link>; })}</nav>;
}
export function LifecyclePanel({ kind, id, path, status, locale, translationExists, translationPublished }: { kind: "domain" | "topic" | "training"; id: string; path: string; status: CatalogueStatus; locale: Locale; translationExists: boolean; translationPublished: boolean }) {
  const canPublish = status === CatalogueStatus.DRAFT || status === CatalogueStatus.ARCHIVED;
  return <aside className="space-y-6 border-t border-[#c8cac0] pt-6"><div><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">ÉTAT DE L&apos;ÉLÉMENT</p><p className="mt-2 text-lg font-semibold">{statusLabel[status]}</p><p className="mt-2 text-sm leading-6 text-[#626862]">L&apos;état du catalogue et la visibilité de chaque langue sont gérés séparément.</p></div>
    <CatalogueActionForm action={lifecycleAction}><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={id} /><input type="hidden" name="path" value={path} />{canPublish && <button name="intent" value="publish" className="wb-focus min-h-10 border border-[#245b49] px-4 text-sm font-medium text-[#245b49]">Publier l&apos;élément</button>}{status !== CatalogueStatus.ARCHIVED && <button name="intent" value="archive" className="wb-focus ml-3 min-h-10 border border-[#a8aaa1] px-4 text-sm">Archiver</button>}{status === CatalogueStatus.DRAFT && <details className="mt-5 border-t border-[#c8cac0] pt-4"><summary className="cursor-pointer text-sm text-red-800">Supprimer ce brouillon</summary><p className="mt-3 text-sm text-[#626862]">Saisissez SUPPRIMER pour confirmer. Cette action reste soumise aux protections de dépendance.</p><label className="mt-3 flex flex-col gap-2 text-sm">Confirmation<input name="confirmation" className="min-h-10 border border-[#a8aaa1] bg-[#fbfaf7] px-3" /></label><button name="intent" value="delete" className="wb-focus mt-3 min-h-10 border border-red-800 px-4 text-sm text-red-800">Supprimer le brouillon</button></details>}</CatalogueActionForm>
    {translationExists && <CatalogueActionForm action={translationPublicationAction}><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={id} /><input type="hidden" name="path" value={path} /><input type="hidden" name="locale" value={locale} /><p className="text-sm text-[#626862]">{localeLabels[locale]} : {translationPublished ? "visible publiquement lorsque l’élément est publié" : "contenu présent, non visible publiquement"}</p><button name="intent" value={translationPublished ? "unpublish" : "publish"} className="wb-focus mt-3 min-h-10 border border-[#a8aaa1] px-4 text-sm">{translationPublished ? "Retirer de la publication" : "Publier cette traduction"}</button></CatalogueActionForm>}
  </aside>;
}
