import { Locale } from "@prisma/client";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/current-admin";
import { adminCatalogueReader, localeLabels } from "@/lib/admin/catalogue.read";
import { saveTopicAction } from "@/lib/admin/catalogue.actions";
import { CatalogueForm } from "../../catalogue-form";
import { CatalogueHeader, LifecyclePanel, LocaleTabs, frenchName } from "../../components";

export default async function TopicDetailPage({ params, searchParams }: PageProps<"/admin/formations/thematiques/[topicId]">) { await requireAdmin(); const { topicId } = await params; const selected = ((await searchParams).locale as Locale) || Locale.FR; const [topic, domains] = await Promise.all([adminCatalogueReader.topic(topicId), adminCatalogueReader.selectors()]); if (!topic) notFound(); const translation = topic.translations.find((item) => item.locale === selected); const path = `/admin/formations/thematiques/${topicId}`; return <div className="space-y-10"><CatalogueHeader title={frenchName(topic.translations)} description="Thématique, domaine parent et présentation traduite." /><div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_18rem]"><section><LocaleTabs path={path} selected={selected} translations={topic.translations} /><div className="mt-7"><CatalogueForm action={saveTopicAction}><input type="hidden" name="id" value={topicId} /><input type="hidden" name="locale" value={selected} /><fieldset className="space-y-5"><legend className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">STRUCTURE ET CONTENU — {localeLabels[selected].toUpperCase()}</legend><label className="flex flex-col gap-2 text-sm font-medium">Domaine<select name="domainId" defaultValue={topic.trainingDomainId} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal">{domains.map((domain) => <option key={domain.id} value={domain.id}>{frenchName(domain.translations)}</option>)}</select></label><label className="flex flex-col gap-2 text-sm font-medium">Nom<input name="name" required defaultValue={translation?.name ?? ""} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label><label className="flex flex-col gap-2 text-sm font-medium">Slug<input name="slug" required defaultValue={translation?.slug ?? ""} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label><label className="flex flex-col gap-2 text-sm font-medium">Ordre d’affichage<input name="displayOrder" type="number" defaultValue={topic.displayOrder} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label></fieldset></CatalogueForm></div></section><LifecyclePanel kind="topic" id={topicId} path={path} status={topic.status} locale={selected} translationExists={Boolean(translation)} translationPublished={translation?.isPublished ?? false} /></div></div>; }
