import Link from "next/link";
import { Locale } from "@prisma/client";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/current-admin";
import { adminExpertsReader } from "@/lib/admin/experts.read";
import { saveExpertAction } from "@/lib/admin/experts.actions";
import { ExpertControls, Header, LocaleTabs, sessionLabel } from "../components";
import { ExpertForm } from "../expert-form";
const date = (value: Date) => new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(value);
export default async function ExpertDetailPage({ params, searchParams }: { params: Promise<{ expertId: string }>; searchParams: Promise<{ locale?: string }> }) { await requireAdmin(); const { expertId } = await params, requested = (await searchParams).locale; const selected = requested === Locale.EN || requested === Locale.PT ? requested : Locale.FR; const expert = await adminExpertsReader.detail(expertId); if (!expert) notFound(); const translation = expert.translations.find((item) => item.locale === selected); const path = `/admin/experts/${expertId}`; return <div className="space-y-10"><Header title={expert.name} description="Identité professionnelle, présentation traduite et relations de session." action={<Link href="/admin/experts" className="wb-focus inline-flex min-h-10 items-center border-b border-current text-sm font-medium">Retour aux experts</Link>} /><div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_18rem]"><section><LocaleTabs path={path} selected={selected} translations={expert.translations} /><div className="mt-7"><ExpertForm action={saveExpertAction} id={expert.id} locale={selected} initial={{ name: expert.name, displayOrder: expert.displayOrder, portraitReference: expert.portraitReference ?? "", professionalTitle: translation?.professionalTitle ?? "", specialization: translation?.specialization ?? "", biography: translation?.biography ?? "" }} /></div><section className="mt-12 border-t border-[#c8cac0] pt-7"><p className="wb-mono text-xs tracking-[.16em] text-[#245b49]">SESSIONS ASSOCIÉES</p><p className="mt-3 text-sm text-[#626862]">Les 20 sessions les plus récentes. Les relations historiques restent visibles après désactivation.</p><ul className="mt-5 divide-y divide-[#c8cac0]">{expert.sessionAssignments.length ? expert.sessionAssignments.map(({ trainingSession }) => <li key={trainingSession.id} className="py-4"><Link href={`/admin/sessions/${trainingSession.id}`} className="wb-focus flex flex-wrap justify-between gap-3"><span><span className="font-medium">{trainingSession.training.translations[0]?.title ?? "Formation sans titre français"}</span><span className="mt-1 block text-sm text-[#626862]">{date(trainingSession.startDate)} — {date(trainingSession.endDate)}</span></span><span className="text-sm">{sessionLabel[trainingSession.status]}</span></Link></li>) : <li className="py-4 text-sm text-[#626862]">Aucune session associée à cet expert.</li>}</ul></section></section><ExpertControls id={expert.id} status={expert.status} locale={selected} translation={translation} /></div></div>; }
