import Link from "next/link";
import { ExpertStatus, Locale, SessionStatus } from "@prisma/client";
import { expertLifecycleAction, expertTranslationPublicationAction } from "@/lib/admin/experts.actions";
import { CatalogueActionForm } from "../formations/catalogue-form";
export const statusLabel: Record<ExpertStatus, string> = { ACTIVE: "Expert actif", INACTIVE: "Ancien / inactif" };
export const sessionLabel: Record<SessionStatus, string> = { DRAFT: "Brouillon", OPEN: "Inscriptions ouvertes", CLOSED: "Inscriptions clôturées", COMPLETED: "Terminée", CANCELLED: "Annulée" };
export const profile = (translations: { locale: Locale; professionalTitle: string | null; specialization: string | null }[]) => translations.find((item) => item.locale === Locale.FR);
export function Header({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <header className="flex flex-wrap items-end justify-between gap-6 border-b border-[#18211d] pb-7"><div><p className="wb-mono text-xs tracking-[.16em] text-[#245b49]">EXPERTS</p><h1 className="mt-4 text-3xl font-semibold tracking-[-.035em] md:text-4xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#626862]">{description}</p></div>{action}</header>; }
export function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="wb-focus inline-flex min-h-11 items-center bg-[#15382f] px-5 py-2 text-sm font-medium text-white">{children}</Link>; }
export function LocaleTabs({ path, selected, translations }: { path: string; selected: Locale; translations: { locale: Locale; isPublished: boolean }[] }) { return <nav aria-label="Langue de présentation" className="flex flex-wrap gap-x-5 border-b border-[#c8cac0] pb-3">{([Locale.FR, Locale.EN, Locale.PT] as const).map((locale) => { const entry = translations.find((item) => item.locale === locale); return <Link key={locale} href={`${path}?locale=${locale}`} aria-current={locale === selected ? "page" : undefined} className={`wb-focus border-b-2 pb-2 text-sm ${locale === selected ? "border-[#245b49] font-semibold" : "border-transparent text-[#626862]"}`}>{locale} <span className="text-xs">{entry ? entry.isPublished ? "· publiée" : "· non publiée" : "· à renseigner"}</span></Link>; })}</nav>; }
export function ExpertControls({ id, status, locale, translation }: { id: string; status: ExpertStatus; locale: Locale; translation?: { isPublished: boolean } }) { const active = status === ExpertStatus.ACTIVE; return <aside className="space-y-7 border-t border-[#c8cac0] pt-6"><div><p className="wb-mono text-xs tracking-[.16em] text-[#245b49]">STATUT</p><p className="mt-2 text-lg font-semibold">{statusLabel[status]}</p><p className="mt-2 text-sm leading-6 text-[#626862]">L’état détermine uniquement l’usage courant, jamais l’effacement des sessions historiques.</p></div><CatalogueActionForm action={expertLifecycleAction}><input type="hidden" name="id" value={id} /><button name="intent" value={active ? "deactivate" : "activate"} className="wb-focus min-h-10 border border-[#245b49] px-4 text-sm text-[#245b49]">{active ? "Désactiver l’expert" : "Réactiver l’expert"}</button></CatalogueActionForm>{translation && <CatalogueActionForm action={expertTranslationPublicationAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="locale" value={locale} /><p className="text-sm text-[#626862]">Présentation {translation.isPublished ? "publiée" : "non publiée"} indépendamment du statut de l’expert.</p><button name="intent" value={translation.isPublished ? "unpublish" : "publish"} className="wb-focus mt-3 min-h-10 border border-[#a8aaa1] px-4 text-sm">{translation.isPublished ? "Retirer de la publication" : "Publier cette présentation"}</button></CatalogueActionForm>}</aside>; }
