import "server-only";
import { EngagementStatus, EngagementType, EngagementVisibility, Locale, Prisma, PrismaClient } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ClientWorkDomainError, type ClientWorkErrorCode } from "./client-work.errors";
import { assertEngagementType, assertLocale, normalizeCountry, normalizeEngagementDates, normalizeOptionalText, normalizeOrganizationName } from "./client-work.validation";

function fail(code: ClientWorkErrorCode, message: string): never { throw new ClientWorkDomainError(code, message); }
export type OrganizationInput = { name: string; logoReference?: string | null; country?: string | null };
export type UpdateOrganizationInput = { name?: string; logoReference?: string | null; country?: string | null };
export type EngagementInput = { clientOrganizationId: string; type: EngagementType; startDate?: Date | null; endDate?: Date | null };
export type EngagementUpdate = { startDate?: Date | null; endDate?: Date | null; type?: EngagementType; clientOrganizationId?: string };
export function createClientWorkService(client: PrismaClient, today = () => new Date()) {
  async function org(tx: Prisma.TransactionClient, id: string) { const item = await tx.clientOrganization.findUnique({ where: { id } }); if (!item) fail("CLIENT_ORGANIZATION_NOT_FOUND", "Client organization was not found."); return item; }
  async function engagement(tx: Prisma.TransactionClient, id: string) { const item = await tx.clientEngagement.findUnique({ where: { id } }); if (!item) fail("CLIENT_ENGAGEMENT_NOT_FOUND", "Client engagement was not found."); return item; }
  async function setVisibility(id: string, visibility: EngagementVisibility) { return client.$transaction(async tx => { await engagement(tx, id); const r = await tx.clientEngagement.updateMany({ where: { id }, data: { visibility } }); if (!r.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Engagement changed concurrently."); return engagement(tx, id); }); }
  return {
    async createClientOrganization(input: OrganizationInput) { return client.clientOrganization.create({ data: { name: normalizeOrganizationName(input.name), logoReference: normalizeOptionalText(input.logoReference), country: input.country ? normalizeCountry(input.country) : null } }); },
    async updateClientOrganization(id: string, input: UpdateOrganizationInput) { return client.$transaction(async tx => { const current = await org(tx, id); const result = await tx.clientOrganization.updateMany({ where: { id, isActive: current.isActive }, data: { name: input.name === undefined ? current.name : normalizeOrganizationName(input.name), logoReference: input.logoReference === undefined ? current.logoReference : normalizeOptionalText(input.logoReference), country: input.country === undefined ? current.country : input.country ? normalizeCountry(input.country) : null } }); if (!result.count) fail("STALE_CLIENT_ORGANIZATION_STATE", "Organization changed concurrently."); return org(tx, id); }); },
    async deactivateClientOrganization(id: string) { return client.$transaction(async tx => { const current = await org(tx, id); if (!current.isActive) fail("STALE_CLIENT_ORGANIZATION_STATE", "Organization is already inactive."); const r = await tx.clientOrganization.updateMany({ where: { id, isActive: true }, data: { isActive: false } }); if (!r.count) fail("STALE_CLIENT_ORGANIZATION_STATE", "Organization changed concurrently."); return org(tx, id); }); },
    async activateClientOrganization(id: string) { return client.$transaction(async tx => { const current = await org(tx, id); if (current.isActive) fail("STALE_CLIENT_ORGANIZATION_STATE", "Organization is already active."); const r = await tx.clientOrganization.updateMany({ where: { id, isActive: false }, data: { isActive: true } }); if (!r.count) fail("STALE_CLIENT_ORGANIZATION_STATE", "Organization changed concurrently."); return org(tx, id); }); },
    async createClientEngagement(input: EngagementInput) { assertEngagementType(input.type); const dates = normalizeEngagementDates(input.startDate ?? null, input.endDate ?? null); return client.$transaction(async tx => { await org(tx, input.clientOrganizationId); return tx.clientEngagement.create({ data: { clientOrganizationId: input.clientOrganizationId, type: input.type, ...dates } }); }); },
    async updateClientEngagement(id: string, input: EngagementUpdate) { return client.$transaction(async tx => { const current = await engagement(tx, id); if (current.status === EngagementStatus.COMPLETED && (input.clientOrganizationId !== undefined || input.type !== undefined || input.startDate !== undefined || input.endDate !== undefined)) fail("ENGAGEMENT_IMMUTABLE", "Completed engagement facts are immutable."); const dates = normalizeEngagementDates(input.startDate === undefined ? current.startDate : input.startDate, input.endDate === undefined ? current.endDate : input.endDate); if (input.clientOrganizationId) await org(tx, input.clientOrganizationId); const r = await tx.clientEngagement.updateMany({ where: { id, status: current.status }, data: { clientOrganizationId: input.clientOrganizationId ?? current.clientOrganizationId, type: input.type ?? current.type, ...dates } }); if (!r.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Engagement changed concurrently."); return engagement(tx, id); }); },
    async completeClientEngagement(id: string) { return client.$transaction(async tx => { const current = await engagement(tx, id); if (current.status !== EngagementStatus.DRAFT) fail("INVALID_ENGAGEMENT_TRANSITION", "Only draft engagements may be completed."); const dates = normalizeEngagementDates(current.startDate, current.endDate); if (!dates.startDate || !dates.endDate || dates.endDate > today()) fail("INVALID_ENGAGEMENT_TRANSITION", "Completion requires concluded dates."); const r = await tx.clientEngagement.updateMany({ where: { id, status: EngagementStatus.DRAFT }, data: { status: EngagementStatus.COMPLETED } }); if (!r.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Engagement changed concurrently."); return engagement(tx, id); }); },
    async makeClientEngagementPublic(id: string) { return setVisibility(id, EngagementVisibility.PUBLIC); },
    async makeClientEngagementPrivate(id: string) { return setVisibility(id, EngagementVisibility.PRIVATE); },
    async deleteClientEngagementDraft(id: string) { return client.$transaction(async tx => { const current = await engagement(tx, id); if (current.status !== EngagementStatus.DRAFT) fail("ENGAGEMENT_IMMUTABLE", "Completed engagements must be preserved."); const r = await tx.clientEngagement.deleteMany({ where: { id, status: EngagementStatus.DRAFT } }); if (!r.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Engagement changed concurrently."); }); },
    async upsertClientEngagementTranslation(id: string, input: { locale: Locale; title: string; description?: string | null }) { assertLocale(input.locale); const data = { title: input.title.trim(), description: normalizeOptionalText(input.description) }; return client.$transaction(async tx => { await engagement(tx, id); const where = { clientEngagementId_locale: { clientEngagementId: id, locale: input.locale } }; const existing = await tx.clientEngagementTranslation.findUnique({ where }); if (!existing) { const created = await tx.clientEngagementTranslation.createMany({ data: { clientEngagementId: id, locale: input.locale, ...data }, skipDuplicates: true }); if (!created.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Translation changed concurrently."); return tx.clientEngagementTranslation.findUnique({ where }); } if (existing.isPublished && !data.title) fail("INVALID_ENGAGEMENT_TRANSLATION", "Published translation title is required."); const r = await tx.clientEngagementTranslation.updateMany({ where: data.title ? { id: existing.id } : { id: existing.id, isPublished: false }, data }); if (!r.count) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Translation changed concurrently."); return tx.clientEngagementTranslation.findUnique({ where: { id: existing.id } }); }); },
    async publishClientEngagementTranslation(id: string, locale: Locale, published = true) { assertLocale(locale); return client.$transaction(async tx => { const tr = await tx.clientEngagementTranslation.findUnique({ where: { clientEngagementId_locale: { clientEngagementId: id, locale } } }); if (!tr) fail("ENGAGEMENT_TRANSLATION_NOT_FOUND", "Engagement translation was not found."); if (published && !tr.title.trim()) fail("INVALID_ENGAGEMENT_TRANSLATION", "Translation title is required."); const r = await tx.clientEngagementTranslation.updateMany({ where: { id: tr.id, isPublished: !published, ...(published && { title: tr.title }) }, data: { isPublished: published } }); if (!r.count && tr.isPublished !== published) fail("STALE_CLIENT_ENGAGEMENT_STATE", "Translation changed concurrently."); return tx.clientEngagementTranslation.findUnique({ where: { id: tr.id } }); }); },
    unpublishClientEngagementTranslation(id: string, locale: Locale) { return this.publishClientEngagementTranslation(id, locale, false); },
  };
}
export const clientWorkService = createClientWorkService(prisma);
