import { servicesEn } from "./services.en";
import type { PublicDictionary } from "./types";

export const en: PublicDictionary = {
  localeName: "English",
  skipToContent: "Skip to content",
  navigation: "Main navigation",
  contact: "Contact us",
  menu: "Menu",
  closeMenu: "Close menu",
  descriptor: "Professional training in insurance, project management and statistics.",
  preparing: "Our institutional website is being prepared.",
  notFound: "Page not found",
  error: "Something went wrong",
  homeNav: "Home",
  trainingsNav: "Training",
  aboutNav: "About",
  servicesNav: "Services",
  languageSelector: "Choose language",
  trainingCatalogue: {
    metaTitle: "Training",
    metaDescription:
      "Explore professional training programmes published by W'BAKENEL Consulting Institute.",
    eyebrow: "TRAINING",
    title: "Training designed for professionals.",
    description:
      "Explore W'BAKENEL Consulting Institute's published programmes, with priority given to the insurance sector.",
    insuranceNote: "Insurance is our priority area of specialisation.",
    programmeLabel: "Published programme",
    domainLabel: "Domain",
    topicLabel: "Topic",
    detailLabel: "View programme",
    enquiryLabel: "Contact us about this training",
    emptyTitle: "No training is published at the moment.",
    emptyDescription: "New published programmes will appear here.",
    unavailableTitle: "The catalogue is temporarily unavailable.",
    unavailableDescription: "Please try again later or contact our team on WhatsApp.",
    previousPage: "Previous",
    nextPage: "Next",
    pageLabel: "Page",
    contactEyebrow: "LET'S TALK",
    contactTitle: "A question about a programme?",
    contactDescription: "Our team is available on WhatsApp to discuss your training needs.",
    contactCta: "Message us on WhatsApp",
  },
  trainingDetail: {
    metadataDescription:
      "Professional training programme published by W'BAKENEL Consulting Institute.",
    backToCatalogue: "All training programmes",
    programmeLabel: "PUBLISHED PROGRAMME",
    domainLabel: "Domain",
    topicLabel: "Topic",
    descriptionLabel: "About this training",
    objectivesLabel: "Objectives",
    audienceLabel: "Intended audience",
    programmeContentLabel: "Programme content",
    unavailableTitle: "This programme is temporarily unavailable.",
    unavailableDescription: "Please try again later or contact our team on WhatsApp.",
    sessionsEyebrow: "UPCOMING SESSIONS",
    sessionsTitle: "Upcoming sessions",
    sessionsDescription: "View the upcoming sessions for this programme.",
    sessionsEmpty: "No upcoming session is currently listed for this programme.",
    sessionsUnavailable: "Sessions are temporarily unavailable. Please try again later.",
    datesLabel: "Dates",
    deliveryLabel: "Delivery",
    locationLabel: "Location",
    priceLabel: "Price",
    registrationLabel: "Availability",
    onlineLabel: "Online",
    inPersonLabel: "In person",
    locationPending: "Location to be confirmed",
    onRequestLabel: "On request",
    pricePending: "Price to be confirmed",
    registrationOpen: "Enquiries open",
    registrationClosed: "Enquiries closed",
    sessionEnquiryLabel: "Ask about this session",
    futureSessionsTitle: "Interested in future sessions?",
    futureSessionsDescription: "Contact W'BAKENEL to ask about upcoming training opportunities.",
    futureSessionsCta: "Ask about future sessions",
    contactEyebrow: "LET'S TALK",
    contactTitle: "A question about this programme?",
    contactDescription: "Our team is available on WhatsApp to discuss your needs.",
    contactCta: "Message us on WhatsApp",
  },
  home: {
    eyebrow: "W'BAKENEL CONSULTING INSTITUTE",
    heroTitle: "Building the skills that move organisations forward.",
    heroDescription:
      "W'BAKENEL Consulting Institute offers professional training in insurance, project management and statistics, with priority given to the insurance sector.",
    heroImageAlt: "Professionals gathered around a laptop during a training session.",
    trainingCta: "Explore our training",
    heroContactCta: "Contact us",
    domainsDetailCta: "Learn more about professional training",
    trainingEyebrow: "PUBLISHED TRAINING",
    trainingTitle: "Explore available programmes.",
    trainingDescription: "A selection of programmes currently published in your language.",
    trainingEmpty:
      "No training is currently available in this language. Our team is available to discuss your needs.",
    trainingUnavailable:
      "The training list is temporarily unavailable. Please try again later or contact our team on WhatsApp.",
    trainingNoSummary: "Programme overview coming soon.",
    introductionEyebrow: "OUR INSTITUTE",
    introductionTitle: "A training institute serving professionals and organisations.",
    introductionDescription:
      "Professional training is the core activity of W'BAKENEL Consulting Institute. Our approach connects the realities of professional practice with skills development, helping individuals and teams progress.",
    complementaryEyebrow: "COMPLEMENTARY SERVICES",
    complementaryTitle: "Beyond training.",
    complementaryDescription:
      "W'BAKENEL also offers consulting, studies and audits, and management-system support. Their scope is defined with each organisation.",
    complementaryOverviewCta: "View all our services",
    contactEyebrow: "LET'S TALK",
    contactTitle: "Let's discuss your training needs.",
    contactDescription:
      "Whether you are considering training for yourself or your team, or need one of our complementary services, our team is available on WhatsApp.",
    contactCta: "Message us on WhatsApp",
  },
  trainingDomains: {
    eyebrow: "THREE DOMAINS",
    title: "Our training domains",
    description:
      "Our professional training is organised around three domains, with priority given to the insurance sector.",
    priorityLabel: "Priority domain",
    note: "The content, intended participants and arrangements of each programme are specified when it is published or in discussion with our team.",
    items: {
      assurance: {
        name: "Insurance",
        description:
          "Our principal specialisation: training for professionals in the insurance sector and the organisations that work within it, strengthening the skills their roles require.",
      },
      gestionProjet: {
        name: "Project management",
        description:
          "Training to help prepare, organise and monitor projects, and to strengthen project-steering practices within teams.",
      },
      statistique: {
        name: "Statistics",
        description:
          "Training in collecting, analysing and interpreting data, so that professional decisions rest on rigorous analysis.",
      },
    },
  },
  services: servicesEn,
};
