import Link from "next/link";
import { SessionStatus } from "@prisma/client";
import { assignSessionExpertAction, removeSessionExpertAction, sessionLifecycleAction } from "@/lib/admin/sessions.actions";
import { CatalogueActionForm } from "../formations/catalogue-form";

export const statusLabel: Record<SessionStatus, string> = { DRAFT: "Brouillon", OPEN: "Inscriptions ouvertes", CLOSED: "Inscriptions clôturées", COMPLETED: "Terminée", CANCELLED: "Annulée" };
export const displayDate = (value: Date) => new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(value);
export const dateInput = (value: Date | null) => value ? value.toISOString().slice(0, 10) : "";
export const sessionPrice = (session: { pricingMode: string; price: { toString(): string } | null; currency: string | null }) => session.pricingMode === "ON_REQUEST" ? "Sur devis" : session.price ? `${new Intl.NumberFormat("fr-FR").format(Number(session.price.toString()))} ${session.currency === "XOF" ? "CFA" : session.currency ?? ""}` : "Prix à préciser";
export const sessionLocation = (session: { deliveryMode: string; city: string | null; venue: string | null }) => session.deliveryMode === "ONLINE" ? "En ligne" : [session.city, session.venue].filter(Boolean).join(" · ") || "Lieu à confirmer";

export function SessionHeader({ title, description, actions }: { title: string; description: string; actions?: React.ReactNode }) { return <header className="flex flex-wrap items-end justify-between gap-6 border-b border-[#18211d] pb-7"><div><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">SESSIONS</p><h1 className="mt-4 text-3xl font-semibold tracking-[-0.035em] md:text-4xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#626862]">{description}</p></div>{actions}</header>; }
export function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="wb-focus inline-flex min-h-11 items-center bg-[#15382f] px-5 py-2 text-sm font-medium text-white hover:bg-[#245b49]">{children}</Link>; }
export function LifecyclePanel({ id, status }: { id: string; status: SessionStatus }) { const actions = status === "DRAFT" ? [["open", "Ouvrir les inscriptions"], ["cancel", "Annuler"]] : status === "OPEN" ? [["close", "Clôturer les inscriptions"], ["cancel", "Annuler"]] : status === "CLOSED" ? [["open", "Rouvrir les inscriptions"], ["complete", "Marquer comme terminée"], ["cancel", "Annuler"]] : []; return <aside className="border-t border-[#c8cac0] pt-6"><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">ÉTAT</p><p className="mt-2 text-lg font-semibold">{statusLabel[status]}</p>{actions.length ? <CatalogueActionForm action={sessionLifecycleAction}><input type="hidden" name="id" value={id} /><div className="mt-5 flex flex-wrap gap-3">{actions.map(([intent, label]) => <button key={intent} name="intent" value={intent} className={`wb-focus min-h-10 border px-4 text-sm ${intent === "cancel" ? "border-red-800 text-red-800" : "border-[#245b49] text-[#245b49]"}`}>{label}</button>)}</div></CatalogueActionForm> : <p className="mt-3 text-sm leading-6 text-[#626862]">Cette session historique est préservée en lecture seule.</p>}</aside>; }
export function Trainers({ id, assignments, experts, mutable }: { id: string; assignments: { expert: { id: string; name: string; status: string; translations: { professionalTitle: string | null }[] } }[]; experts: { id: string; name: string; translations: { professionalTitle: string | null }[] }[]; mutable: boolean }) { const assigned = new Set(assignments.map((entry) => entry.expert.id)); return <section className="border-t border-[#c8cac0] pt-7"><p className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">FORMATEURS</p><ul className="mt-4 divide-y divide-[#c8cac0]">{assignments.length ? assignments.map(({ expert }) => <li key={expert.id} className="flex items-center justify-between gap-4 py-3"><span><span className="font-medium">{expert.name}</span>{expert.translations[0]?.professionalTitle && <span className="ml-2 text-sm text-[#626862]">{expert.translations[0].professionalTitle}</span>}{expert.status !== "ACTIVE" && <span className="ml-2 text-xs text-[#8a5b16]">ancien expert</span>}</span>{mutable && <CatalogueActionForm action={removeSessionExpertAction}><input type="hidden" name="id" value={id} /><button name="expertId" value={expert.id} className="wb-focus text-sm text-red-800">Retirer</button></CatalogueActionForm>}</li>) : <li className="py-3 text-sm text-[#626862]">Aucun formateur affecté.</li>}</ul>{mutable && <CatalogueActionForm action={assignSessionExpertAction}><input type="hidden" name="id" value={id} /><label className="mt-5 flex flex-col gap-2 text-sm font-medium">Ajouter un expert actif<select name="expertId" className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal"><option value="">Sélectionner</option>{experts.filter((expert) => !assigned.has(expert.id)).map((expert) => <option key={expert.id} value={expert.id}>{expert.name}{expert.translations[0]?.professionalTitle ? ` — ${expert.translations[0].professionalTitle}` : ""}</option>)}</select></label><button className="wb-focus mt-3 min-h-10 border border-[#245b49] px-4 text-sm text-[#245b49]">Ajouter</button></CatalogueActionForm>}</section>; }
