"use client";

import { useActionState, useMemo, useState } from "react";
import type { SessionActionState } from "@/lib/admin/sessions.actions";

type Action = (state: SessionActionState, formData: FormData) => Promise<SessionActionState>;
type Training = { id: string; translations: { title: string }[]; trainingTopic: { translations: { name: string }[]; trainingDomain: { translations: { name: string }[] } } };
type Expert = { id: string; name: string; translations: { professionalTitle: string | null }[] };
type Initial = { startDate: string; endDate: string; registrationDeadline: string; deliveryMode: "IN_PERSON" | "ONLINE"; country: string; city: string; venue: string; pricingMode: "FIXED" | "ON_REQUEST"; price: string; currency: string; capacity: string };
const fr = (items: { title?: string; name?: string }[], fallback: string) => items[0]?.title ?? items[0]?.name ?? fallback;
const regionName = (code: string) => { try { return /^[A-Z]{2}$/.test(code) ? new Intl.DisplayNames(["fr"], { type: "region" }).of(code) ?? "" : ""; } catch { return ""; } };

export function SessionForm({ action, trainings, experts, initial, sessionId, mutable = true }: { action: Action; trainings?: Training[]; experts?: Expert[]; initial: Initial; sessionId?: string; mutable?: boolean }) {
  const [state, formAction, pending] = useActionState(action, {});
  const [delivery, setDelivery] = useState(initial.deliveryMode), [pricing, setPricing] = useState(initial.pricingMode), [country, setCountry] = useState(initial.country);
  const countryLabel = useMemo(() => regionName(country.trim().toUpperCase()), [country]);
  return <form action={formAction} className="space-y-8">
    {sessionId && <input type="hidden" name="id" value={sessionId} />}
    {trainings && <fieldset className="space-y-4"><legend className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">FORMATION</legend><label className="flex flex-col gap-2 text-sm font-medium">Formation<select name="trainingId" required disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100"><option value="">Sélectionner une formation</option>{trainings.map((training) => <option key={training.id} value={training.id}>{fr(training.trainingTopic.trainingDomain.translations, "Domaine")} → {fr(training.trainingTopic.translations, "Thématique")} → {fr(training.translations, "Formation sans titre français")}</option>)}</select></label></fieldset>}
    <fieldset className="grid gap-5 border-t border-[#c8cac0] pt-7 sm:grid-cols-2"><legend className="wb-mono col-span-full text-xs tracking-[0.16em] text-[#245b49]">PLANIFICATION</legend><label className="flex flex-col gap-2 text-sm font-medium">Début<input name="startDate" type="date" required defaultValue={initial.startDate} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label><label className="flex flex-col gap-2 text-sm font-medium">Fin<input name="endDate" type="date" required defaultValue={initial.endDate} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label><label className="flex flex-col gap-2 text-sm font-medium">Date limite d&apos;inscription <span className="font-normal text-[#626862]">(optionnelle)</span><input name="registrationDeadline" type="date" defaultValue={initial.registrationDeadline} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label></fieldset>
    <fieldset className="grid gap-5 border-t border-[#c8cac0] pt-7 sm:grid-cols-2"><legend className="wb-mono col-span-full text-xs tracking-[0.16em] text-[#245b49]">MODALITÉ</legend><label className="flex flex-col gap-2 text-sm font-medium">Mode<select name="deliveryMode" value={delivery} disabled={!mutable} onChange={(event) => setDelivery(event.target.value as typeof delivery)} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100"><option value="IN_PERSON">Présentiel</option><option value="ONLINE">En ligne</option></select></label>{delivery === "IN_PERSON" && <><label className="flex flex-col gap-2 text-sm font-medium">Pays <span className="font-normal text-[#626862]">(code ISO, ex. BF)</span><input name="country" required value={country} disabled={!mutable} onChange={(event) => setCountry(event.target.value)} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" />{countryLabel && <span className="text-xs font-normal text-[#626862]">{countryLabel}</span>}</label><label className="flex flex-col gap-2 text-sm font-medium">Ville<input name="city" required defaultValue={initial.city} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label><label className="flex flex-col gap-2 text-sm font-medium">Lieu <span className="font-normal text-[#626862]">(optionnel)</span><input name="venue" defaultValue={initial.venue} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label></>} {delivery === "ONLINE" && <p className="self-end text-sm leading-6 text-[#626862]">Session à distance planifiée. Aucun lieu physique n’est conservé.</p>}</fieldset>
    <fieldset className="grid gap-5 border-t border-[#c8cac0] pt-7 sm:grid-cols-2"><legend className="wb-mono col-span-full text-xs tracking-[0.16em] text-[#245b49]">TARIFICATION</legend><label className="flex flex-col gap-2 text-sm font-medium">Mode<select name="pricingMode" value={pricing} disabled={!mutable} onChange={(event) => setPricing(event.target.value as typeof pricing)} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100"><option value="FIXED">Prix fixe</option><option value="ON_REQUEST">Sur devis</option></select></label>{pricing === "FIXED" && <><label className="flex flex-col gap-2 text-sm font-medium">Prix<input name="price" inputMode="decimal" required defaultValue={initial.price} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label><label className="flex flex-col gap-2 text-sm font-medium">Devise<input name="currency" required defaultValue={initial.currency || "XOF"} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal uppercase disabled:bg-stone-100" /><span className="text-xs font-normal text-[#626862]">XOF est présenté CFA.</span></label></>} {pricing === "ON_REQUEST" && <p className="self-end text-sm leading-6 text-[#626862]">Sur devis : aucun prix ni devise ne seront enregistrés.</p>}</fieldset>
    <fieldset className="border-t border-[#c8cac0] pt-7"><legend className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">CAPACITÉ</legend><label className="mt-4 flex max-w-xs flex-col gap-2 text-sm font-medium">Participants <span className="font-normal text-[#626862]">(optionnel)</span><input name="capacity" type="number" min="1" step="1" defaultValue={initial.capacity} disabled={!mutable} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal disabled:bg-stone-100" /></label><p className="mt-2 text-sm text-[#626862]">Capacité configurée, sans calcul de places restantes.</p></fieldset>
    {experts && <fieldset className="border-t border-[#c8cac0] pt-7"><legend className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">FORMATEURS</legend><p className="mt-3 text-sm text-[#626862]">Sélectionnez un ou plusieurs experts actifs.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{experts.map((expert) => <label key={expert.id} className="flex items-start gap-3 border border-[#c8cac0] p-3 text-sm"><input name="expertIds" type="checkbox" value={expert.id} disabled={!mutable} className="mt-1" /><span><span className="font-medium">{expert.name}</span>{expert.translations[0]?.professionalTitle && <span className="block text-[#626862]">{expert.translations[0].professionalTitle}</span>}</span></label>)}</div></fieldset>}
    {state.error && <p role="alert" className="border-l-2 border-red-700 py-2 pl-3 text-sm leading-6 text-red-800">{state.error}</p>}
    {mutable && <button type="submit" disabled={pending} className="min-h-11 bg-[#15382f] px-5 py-2 text-sm font-medium text-white disabled:opacity-60">{pending ? "Enregistrement…" : sessionId ? "Enregistrer les modifications" : "Créer la session"}</button>}
  </form>;
}
