import { Locale } from "@prisma/client";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth/current-admin";
import { adminCatalogueReader, localeLabels } from "@/lib/admin/catalogue.read";
import { saveDomainAction } from "@/lib/admin/catalogue.actions";
import { CatalogueHeader, LifecyclePanel, LocaleTabs, frenchName } from "../../components";
import { CatalogueForm } from "../../catalogue-form";

export default async function DomainDetailPage({ params, searchParams }: PageProps<"/admin/formations/domaines/[domainId]">) { await requireAdmin(); const { domainId } = await params; const selected = ((await searchParams).locale as Locale) || Locale.FR; const domain = await adminCatalogueReader.domain(domainId); if (!domain) notFound(); const translation = domain.translations.find((item) => item.locale === selected); const path = `/admin/formations/domaines/${domainId}`; return <div className="space-y-10"><CatalogueHeader title={frenchName(domain.translations)} description="Domaine de formation et présentation traduite." /><div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_18rem]"><section><LocaleTabs path={path} selected={selected} translations={domain.translations} /><div className="mt-7"><CatalogueForm action={saveDomainAction}><input type="hidden" name="id" value={domainId} /><input type="hidden" name="locale" value={selected} /><fieldset className="space-y-5"><legend className="wb-mono text-xs tracking-[0.16em] text-[#245b49]">CONTENU — {localeLabels[selected].toUpperCase()}</legend><label className="flex flex-col gap-2 text-sm font-medium">Nom<input name="name" required defaultValue={translation?.name ?? ""} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label><label className="flex flex-col gap-2 text-sm font-medium">Slug<input name="slug" required defaultValue={translation?.slug ?? ""} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label><label className="flex flex-col gap-2 text-sm font-medium">Ordre d’affichage<input name="displayOrder" type="number" defaultValue={domain.displayOrder} className="min-h-11 border border-[#a8aaa1] bg-[#fbfaf7] px-3 font-normal" /></label></fieldset></CatalogueForm></div></section><LifecyclePanel kind="domain" id={domainId} path={path} status={domain.status} locale={selected} translationExists={Boolean(translation)} translationPublished={translation?.isPublished ?? false} /></div></div>; }
